task:
    name: Build on linux
    bazel_info_script:   bazel info  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  release
    build_sample_script: bazel build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //sample/...
    build_all_script:    bazel build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //...
    container:
        image: l.gcr.io/google/bazel:1.2.1
task:
    name: Build on Windows
    install_bazel_script: choco install -y bazel
    bazel_info_script:   bazel info  --remote_http_cache=http://%CIRRUS_HTTP_CACHE_HOST%  release
    build_sample_script: bazel build --remote_http_cache=http://%CIRRUS_HTTP_CACHE_HOST%  //sample/...
    build_all_script:    bazel build --remote_http_cache=http://%CIRRUS_HTTP_CACHE_HOST%  //...
    windows_container:
        image: cirrusci/windowsservercore:2019
        os_version: 2019
    steps:
    - restore_cache:
      keys:
      - chocho-{{ .Branch }}-{{ .Revision }}
      - chocho-{{ .Branch }}-
      - chocho--
      - chocho-
    - checkout
    - git_cache:
      key: chocho-{{ .Branch }}-{{ .Revision }}
      paths:
      - "C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\chocolatey"

