task:
    name: Build on linux
    build_sample_script: bazel build //sample/...
    build_all_script: bazel build //...
    container:
        image: l.gcr.io/google/bazel:1.2.1
task:
    name: Build on Windows
    install_bazel_script: choco install -y bazel
    build_sample_script: bazel build //sample/...
    build_all_script: bazel build //...
    windows_container:
        image: cirrusci/windowsservercore:2019
        os_version: 2019
