task:
    name: Main build
    build_sample_script: bazel build //sample/...
    build_all_script: bazel build //...
    matrix:
      container:
          image: l.gcr.io/google/bazel:1.2.1
      windows_container:
          image: l.gcr.io/google/bazel:1.2.1
          os_version: 2019